
extra-package-dbs: []
packages:
- ./boogaloo
- .
# - ./haskell-z3
extra-deps:
- stream-monad-0.4.0.2
- logict-0.5.0.2
- set-monad-0.3.0.0

- git: https://github.com/IagoAbal/haskell-z3.git
  commit: 009772a23b9900e0e73c7460f8a37762b4b8d3c4

# - optparse-applicative-0.12.0.0


# - ./boogaloo
# - ghc-mod-4.1.6
# - intero-0.1.24
# - stack-run-0.1.1.0

resolver: lts-12.14

ghc-options:
  generic-deriving: -f-base-4-9

# with-gcc: /usr/local/bin/gcc-9

extra-include-dirs: 
  - /usr/local/include
extra-lib-dirs: 
  - /usr/local/lib
  