
extra-package-dbs: []
packages:
- .
- ./boogaloo
# - ./haskell-z3
extra-deps:
- lens-4.13
- z3-4.3.1
- random-1.0.0.0
- mtl-2.1.2
- ansi-wl-pprint-0.6.4
- html-1.0
- parsec-3.1.0
- ansi-terminal-0.5.0
- stream-monad-0.4.0.2
- base-orphans-0.4.0
- tagged-0.7.3
- adjunctions-4.2.1
- free-4.12
- bifunctors-5
- profunctors-5
- semigroupoids-5
- comonad-4.2.7.1
- kan-extensions-4.2.2
- reflection-2.1
- nats-0.1
- logict-0.5.0.2
- text-0.11.3.1
# - optparse-applicative-0.12.0.0
- intero-0.1.24
# - stack-run-0.1.1.0
# - ./boogaloo
# - ghc-mod-4.1.6

resolver: lts-2.0

# extra-include-dirs: 
# - /Library/include
# extra-lib-dirs:
# - /Library/lib

ghc-options:
  generic-deriving: -f-base-4-9