flags:
  generic-deriving:
    base-4-9: false
  # language-boogie:
  #   boogaloo: false
extra-package-dbs: []
packages:
- .
- ../boogaloo
extra-deps:
- lens-4.13
- z3-4.2.0
- random-1.0.0.0
- mtl-2.1.2
- ansi-wl-pprint-0.6.4
- html-1.0
- parsec-3.1.0
- ansi-terminal-0.5.0
- stream-monad-0.4.0.2
- base-orphans-0.4.0
- tagged-0.7.3
- adjunctions-4.2.1
- free-4.12
- bifunctors-5
- profunctors-5
- semigroupoids-5
- comonad-4.2.7.1
- kan-extensions-4.2.2
- reflection-2.1
- nats-0.1
- logict-0.5.0.2
- text-0.11.3.1

resolver: lts-2.0
