void incr ( ref int out ) {
	out = out + 1;
}

void decr (ref int out) {
	out = out - 1;
}

generator int expr(int x, int y, int z, int bnd){
	assert bnd > 0;
	generator int sum(){
		return {| x | y | z|} + {| x | y | z | ?? |};
	}
	if(??) { return sum(); }
	else { return sum() * expr(x,y,z,bnd-1); }
}

void bound(int x, int y) {
	assert x < y;
}
 
void update(int ox, int nx, int oy, int ny) {
	assert ox != nx;
	assert oy != ny;
}

harness void sketch (int x, int y) {
	assume x < y;
	incr_mid (mid);
	int x1 = expr(x,y,1);
	int y1 = expr(x,y,1);
	update(x, x1, y, y1);
	bound(x1, y1);
}