boolean goodConfig(int start, int stop, int run){
	return ((0 <= run && run <= 1) && (0 <= start && start <= 1) && (0 <= stop && stop <= 1) && start != stop && run == start);
}

void cells2colors(int n, int[n] p, int[n] q){
	for(int i=0; i<n; ++i){
		assert p[i] == q[i];
	}
}

void cells2colorsA(int n, int[n] p, int[n] q){
	for(int i=0; i<n; ++i){
		assume p[i] == q[i];
	}
}

generator int[n] arrexpr(int n, int r, int[n] p, ref int[n] q) {
	for(int i=0; i<n; i++){
		if(p[i] == 0){
			q[i] = expr(r, p[i], q[i], 1);
		} else if (p[i] == 1){
			q[i] = expr(r, p[i], q[i], 1);
		}
	}
	return q;
}

generator int expr(int x, int y, int z, int bnd) {
	assert bnd > 0;
	generator int mult(){
		return ?? * {| x | y | ?? |};
	}
	if(??) { return mult(); }
	else { return mult() + expr(x,y,z,bnd-1); }
}

int[n] colorOnClick(int n, ref int[n] rendered, int[n] cells, int locIndex){
	for(int idx=0; idx<n; idx++){
		if(idx == locIndex){
			if(rendered[idx] == 0) {
				rendered[idx] = 1;
			}
			else if(rendered[idx] == 1){
				rendered[idx] = 0;
			}
		}
	}
	return rendered;
}

generator void solveStart(ref int run, int start, ref int stop) {
  if (start == 0) {
      run = expr(start,stop,run,1);
    	stop = expr(start,stop,run,1);
  } else {
      run = expr(start,stop,run,1);
    	stop = expr(start,stop,run,1);
  }
}

generator void solveStop(ref int run, ref int start, int stop) {
  if (start == 0) {
      run = expr(start,stop,run,1);
    	start = expr(start,stop,run,1);
  } else {
      run = expr(start,stop,run,1);
    	start = expr(start,stop,run,1);
  }
}

void toggleButton(ref int it){
	if(it == 0){
		it = 1;
	} else {
    it = 1;
  }
}



int[n] golLogic(int uBound, int n, int[n] cells, int idx, int[n] rendered){
    int count = 0;
    int[n] oldCells;

	for(int i=0; i<n; i++){
		oldCells[i] = cells[i];
	}

	for(int i=0; i<n; i++){
		if(idx == 0){
			if (idx + 1 == uBound) { 
		    } if (idx + 2 == uBound) {
				count = oldCells[idx+1];
        	} else {
				count = oldCells[idx+1] + oldCells[idx+2];
        	}
		}

		if (idx == 1) {
			count = oldCells[idx-1];

        	if (idx + 1 == uBound) {
	        } if (idx + 2 == uBound) {
				count = count + oldCells[idx+1];
        	} else {
				count = count + oldCells[idx+1] + oldCells[idx+2];
        	}
		}

		else {
			count = oldCells[idx-1] + oldCells[idx-2];

        	if (idx + 1 == uBound) {
			} else if (idx + 2 == uBound) {
				count = count + oldCells[idx+1];
        	} else {
				count = count + oldCells[idx+1] + oldCells[idx+2];
        	}
      	}

    	if (oldCells[idx] == 0) {
        	if (count == 2 || count == 3) {
						cells[idx] = 1;
        		}
    	} else {
       		if (count != 2 && count != 4) {
						cells[idx] = 0;
        	}
    	}
  	}
	return cells;
}

int[n] buildGol(int n){
	int[n] out;
    for(int i = 0; i < n; ++i){
        if(i%2==0) {out[i] = 1;}
        else {out[i] = 0;}
    }
    return out;
}

harness void sketch (int start, int stop, int run, int n, int idx) {
	n = 3;
	int[n] rendered = buildGol(n);
	int[n] cells = buildGol(n);
  cells2colorsA(n,cells,rendered);

	int[n] nrendered = colorOnClick(n,rendered,cells,idx);
	int[n] ncells = arrexpr(n, idx, nrendered, cells);

  cells2colors(n,ncells,nrendered);   
  
  assume goodConfig(start, stop, run);
  toggleButton(start);
  solveStart(run, start, stop);
  assert goodConfig(start, stop, run);

	int[n] lcells = golLogic(n,n,cells,1,rendered);
	int[n] lrendered = arrexpr(n,idx,lcells,rendered);
	cells2colors(n, lcells, lrendered);

  toggleButton(stop);
  solveStop(run, start, stop);
  assert goodConfig(start, stop, run);
}
