void cells2colors(int m, int n, int[m][n] p, int[m][n] q){
    for(int i=0; i<m; ++i){
        for(int j=0; j<n; j++) {
            assert p[i][j] == q[i][j];
        }
    }
}

generator int[m][n] arrexpr(int m, int n, int[m][n] p, int[m][n] q) {
    for(int i=0; i<m; ++i){
        for(int j=0; j<n; j++) {
            p[i][j] = expr(p[i][j],q[i][j],i,j);
        }
    }
    return p;
}

generator int expr(int a, int b, int c, int d) {
    generator int sum(){
        return {| a | b | c | d |} * {| a | b | c | d | ?? |};
    }
    if(??) { return sum(); }
    else { return sum() + expr(a,b,c,d); }
}

generator void colorOnClick(int m, int n, int[m][n] rendered, int[m][n] cells, int loci, int locj){
    for(int i=0; i<m; ++i){
        for(int j=0; j<n; j++) {
            if(i == loci && locj == j){
                if(rendered[i][j] == 0) {
                    rendered[i][j] = 1;
                    int[m][n] ncells = arrexpr(m,n,cells,rendered);
                    cells2colors(m, n, ncells, rendered);
                }
                else if(rendered[i][j] == 1){
                    rendered[i][j] = 0;
                    int[m][n] ncells = arrexpr(m,n,cells,rendered);
                    cells2colors(m, n, ncells, rendered);
                }
            }
        }
    }
}

generator void golLogic(int iBound, int jBound, int m, int n, int[m][n] cells, int loci, int locj, int[m][n] rendered){
    int count = 0;
    int[m][n] oldCells;

    for(int i=0; i<m; ++i){
        for(int j=0; j<n; j++) {
            oldCells[i][j] = cells[i][j];
        }
    }

    for(int i=0; i<m; ++i){
        for(int j=0; j<n; j++) {
            if(loci == 0){
                if (locj == 0) {
                    count = oldCells[loci][locj+1] + oldCells[loci+1][locj] + oldCells[loci+1][locj+1];
                } 

                else if(locj+1 == jBound) {
                    count = oldCells[loci][locj-1] + oldCells[loci+1][locj] + oldCells[loci+1][locj-1]; 
                }

                else {
                    count = oldCells[loci][locj-1] + oldCells[loci][locj+1] + oldCells[loci+1][locj-1] + oldCells[loci+1][locj] + oldCells[loci+1][locj+1];
                }
            }

            else if(loci + 1 == iBound){
                if (locj == 0) { 
                    count = oldCells[loci][locj+1] + oldCells[loci-1][locj+1] + oldCells[loci-1][locj];
                }

                else if(locj + 1 == jBound){
                    count = oldCells[loci][locj-1] + oldCells[loci-1][locj-1] + oldCells[loci-1][locj];
                }

                else {
                    count = oldCells[loci][locj-1] + oldCells[loci][locj+1] + oldCells[loci-1][locj-1] + oldCells[loci-1][locj] + oldCells[loci-1][locj+1];
                }
            }

            else {
                if (locj == 0){
                    count = oldCells[loci-1][locj] + oldCells[loci+1][locj] + oldCells[loci-1][locj+1] + oldCells[loci][locj+1] + oldCells[loci+1][locj+1];
                }

                else if(locj+1 == jBound){
                    count = oldCells[loci-1][locj] + oldCells[loci+1][locj] + oldCells[loci-1][locj-1] + oldCells[loci][locj-1] + oldCells[loci+1][locj-1];
                }

                else{
                    count = count + oldCells[loci-1][locj] + oldCells[loci-1][locj-1] + oldCells[loci-1][locj+1] + oldCells[loci+1][locj] + oldCells[loci+1][locj-1] + oldCells[loci+1][locj+1] + oldCells[loci][locj-1] + oldCells[loci][locj+1];
                }
            }

        if (oldCells[loci][locj] == 0) {
            if (count == 2 || count == 3) {
                cells[i][j] = 1;
                int[m][n] nrendered = arrexpr(m,n,rendered,cells);
                cells2colors(m, n, nrendered, cells);
                }
        } else {
            if (count != 2 && count != 4) {
                cells[i][j] = 0;
                int[m][n] nrendered = arrexpr(m,n,rendered,cells);
                cells2colors(m, n, nrendered, cells);
               }
            }
        }
    }
}


int[m][n] buildGol(int m, int n){
    int[m][n] out;
    for(int i=0; i<m; ++i){
        for(int j=0; j<n; j++) {
            if(i%2==0) {out[i][j] = 1;}
            else {out[i][j] = 1;}
        }
    }
    return out;
}

harness void sketch (int start, int stop, int run, int m, int n) {
    m = 6;
    n = 6;
    int[m][n] rendered = buildGol(m,n);
    int[m][n] cells = rendered;
    colorOnClick(m, n, rendered, cells, 1, 1);
    golLogic(m, n, m, n, cells, 1, 2, rendered);

}