void incr ( ref int out ) {
	out = out + 1;
}

generator int expr(int x, int y, int z, int bnd){
	assert bnd > 0;
	generator int sum(){
		return {| x | y | z|} + {| x | y | z | ?? |};
	}
	if(??) { return sum(); }
	else { return sum() * expr(x,y,z,bnd-1); }
}

void midPoint(int x, int y, int mid) {
	assert x + y == 2 * mid;
}
 
void update(int ox, int nx) {
	assert ox != nx;
}

harness void sketch (int x, int y, int mid) {
	assume x + y == 2 * mid;
  assume x != y;
	incr (mid);
	int x1 = expr(x,y,mid,1);
	int y1 = expr(x,y,mid,1);
	update(x, x1);
	update(y, y1);
  update(x1, y1);
	midPoint(x1, y1, mid);


	x = x1;
	y = y1;

	incr (x);
	int m1 = expr(x,y,mid,1);
	y1 = expr(x,y,mid,1);
	update(mid, m1);
	update(y, y1);
  update(x, y1);
	midPoint(x1, y1, m1);

	mid = m1;
	y = y1;

	incr (y);
	x1 = expr(x,y,mid,1);
	m1 = expr(x,y,mid,1);
	update(x, x1);
  update(x1, y);
	update(mid, m1);
	midPoint(x1, y, m1);
	
}