void cells2colors(int n, int[n] p, int[n] q){
	for(int i=0; i<n; ++i){
		assert p[i] == q[i];
	}
}

void goodConfig(int start, int stop, int run){
	assert ((0 <= run && run <= 1) && (0 <= start && start <= 1) && (0 <= stop && stop <= 1) && start != stop && run == start);
}

generator int[n] arrexpr(int n, ref int[n] p, int[n] q) {
	for(int i=0; i<n; i++){
		p[i] = expr(p[i], q[i], i);
	}
	return p;
}

generator int expr(int x, int y, int z) {
	return {| x | y | z|} * {| x | y | z| ?? |};
}

generator void toggleStart(int start, int stop, int run){
	if(start == 0){
		start = 1;
		stop = expr(start,stop,run);
		run = expr(start,stop,run);
		goodConfig(start,stop,run);
    }
    else if(start == 1){
		start = 0;
		stop = expr(start,stop,run);
		run = expr(start,stop,run);
		goodConfig(start,stop,run);
    }
}

generator void toggleStop(int start, int stop, int run){
	if(stop == 0){
		stop = 1;
		start = expr(start,stop,run);
		run = expr(start,stop,run);
		goodConfig(start,stop,run);
    }
    else if(stop == 1){
		stop = 0;
		start = expr(start,stop,run);
		run = expr(start,stop,run);
		goodConfig(start,stop,run);
    }
}

generator void colorOnClick(int n, int[n] rendered, int[n] cells, int locIndex){
	for(int idx=0; idx<n; idx++){
		if(idx == locIndex){
			if(rendered[idx] == 0) {
				rendered[idx] = 1;
				int[n] ncells = arrexpr(n, cells, rendered);
				cells2colors(n, ncells, rendered);
			}
			else if(rendered[idx] == 1){
				rendered[idx] = 0;
				int[n] ncells = arrexpr(n, cells, rendered);
				cells2colors(n, ncells, rendered);
			}
		}
	}
}

generator void golLogic(int uBound, int n, int[n] cells, int idx, int[n] rendered){
    int count = 0;
    int[n] oldCells;

	for(int i=0; i<n; i++){
		oldCells[i] = cells[i];
	}

	for(int i=0; i<n; i++){
		if(idx == 0){
			if (idx + 1 == uBound) { 
		    } if (idx + 2 == uBound) {
				count = oldCells[idx+1];
        	} else {
				count = oldCells[idx+1] + oldCells[idx+2];
        	}
		}

		if (idx == 1) {
			count = oldCells[idx-1];

        	if (idx + 1 == uBound) {
	        } if (idx + 2 == uBound) {
				count = count + oldCells[idx+1];
        	} else {
				count = count + oldCells[idx+1] + oldCells[idx+2];
        	}
		}

		else {
			count = oldCells[idx-1] + oldCells[idx-2];

        	if (idx + 1 == uBound) {
			} else if (idx + 2 == uBound) {
				count = count + oldCells[idx+1];
        	} else {
				count = count + oldCells[idx+1] + oldCells[idx+2];
        	}
      	}

    	if (oldCells[idx] == 0) {
        	if (count == 2 || count == 3) {
				cells[idx] = 1;
				int[n] nrendered = arrexpr(n, rendered, cells);
				cells2colors(n, cells, nrendered);
        		}
    	} else {
       		if (count != 2 && count != 4) {
				cells[idx] = 0;
				int[n] nrendered = arrexpr(n, rendered, cells);
				cells2colors(n, cells, nrendered);
        	}
    	}
  	}
}

harness void sketch (int start, int stop, int run) {
	int[4] rendered = {0, 0, 1, 1};
	int[4] cells = {0, 0, 1, 1};
	toggleStart(0, stop, run);
	toggleStop(start, 0, run);
	colorOnClick(4, rendered, cells, 1);
	golLogic(4, 4, cells, 1, rendered);
}