void equal_arrays(int n, int[n] p, int[n] q){
	for(int i=0; i<n; ++i){
		assert p[i] == q[i];
	}
}

int[n] incr_x(int n, ref int[n] x, ref int[n] y) {
	for(int i=0; i<n; i++){
		x[i] = 2 * y[i];
	}
	return x;
}

generator int[n] expr(int n, int[n] y) {
	for(int i=0; i<n; ++i){
		y[i] = ?? + y[i] / ?? * ??;
	}
	return y;
}

harness void sketch (int a, int b, int c) {
	int[3] x = {a,b,c};
	int[3] y = {a,b,c};
	int[3] x1 = incr_x(3,x,y);
	int[3] y1 = expr(3, y);
	equal_arrays(3, x1, y1);
}